# -*- coding: utf-8 -*-
"""2025ad05008.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HbdazQjSCzOZpnglAQo49RPkweDj4e5o

# Importing all required libraries
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    matthews_corrcoef,
    confusion_matrix,
    classification_report,
    roc_curve
)

import joblib

print("All libraries imported successfully!")

"""# Mount Google Drive"""

from google.colab import drive
drive.mount('/content/drive')

"""# Uploading Dataset"""

#uploading traing dataset and test data set
train = pd.read_csv("/content/drive/MyDrive/ML Assigment/Assignment2/bank-additional-full.csv",sep=";")
original_train = train.copy()
train.head()

"""# Dataset Information"""

# Display the number of rows and columns in the dataset
train.shape

#Summary of dataset
train.info()

"""# Missing Value Analysis"""

#null values
train.isnull().sum()

"""# Target Variable Analysis"""

# Encode Target Variable
train["y"] = train["y"].map({"no": 0, "yes": 1})
train["y"].value_counts()

#Seperating feature and Target
X = train.drop("y", axis=1)
y = train["y"]

print(X.shape)
print(y.shape)

"""# Data Preprocessing"""

# Separating the feature columns into categorical and numerical data types
categorical_cols = X.select_dtypes(include="object").columns
numerical_cols = X.select_dtypes(exclude="object").columns
print("Categorical Columns:")
print(categorical_cols)
print("\nNumerical Columns:")
print(numerical_cols)

# Encode all categorical feature columns into numerical values

label_encoders = {}

for column in X.columns:
    if X[column].dtype == "object":

        encoder = LabelEncoder()

        X[column] = encoder.fit_transform(
            X[column].astype(str)
        )

        label_encoders[column] = encoder

print("Categorical features encoded:")
print(list(label_encoders.keys()))

"""# Train-Test Split"""

from sklearn.model_selection import train_test_split
# Split the dataset into training (80%) and testing (20%) sets
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training Shape:", X_train.shape)
print("Testing Shape:", X_test.shape)

"""# Feature Scaling"""

from sklearn.preprocessing import StandardScaler
#Scaling
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Scaling Completed!")

"""# Logistic Regression"""

#Logistic Regression Model

# Create the model
logistic_model = LogisticRegression(random_state=42, max_iter=1000,class_weight='balanced')

# Train the model
logistic_model.fit(X_train_scaled, y_train)

print("Logistic Regression Model Trained Successfully!")

# Predictions on test data
y_pred_log = logistic_model.predict(X_test_scaled)

# Probability predictions (needed for AUC)
y_prob_log = logistic_model.predict_proba(X_test_scaled)[:, 1]

#calculate all equired matrix
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    matthews_corrcoef
)

accuracy = accuracy_score(y_test, y_pred_log)
precision = precision_score(y_test, y_pred_log)
recall = recall_score(y_test, y_pred_log)
f1 = f1_score(y_test, y_pred_log)
auc = roc_auc_score(y_test, y_prob_log)
mcc = matthews_corrcoef(y_test, y_pred_log)

print("Accuracy :", round(accuracy,4))
print("AUC Score :", round(auc,4))
print("Precision :", round(precision,4))
print("Recall :", round(recall,4))
print("F1 Score :", round(f1,4))
print("MCC :", round(mcc,4))

from sklearn.metrics import confusion_matrix
# Compute the confusion matrix
cm = confusion_matrix(y_test, y_pred_log)

print(cm)

from sklearn.metrics import classification_report
# Generate and display the classification report
print("Classification Report")
print(classification_report(y_test, y_pred_log))

#plot the the confusion matrix
import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay

disp = ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot(cmap="Blues")

plt.title("Logistic Regression - Confusion Matrix")
plt.show()

"""# Decision Tree"""

dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train_scaled, y_train)

#Prediction on test data
y_pred_dt = dt_model.predict(X_test_scaled)
y_prob_dt = dt_model.predict_proba(X_test_scaled)[:, 1]

# Calculate the performance evaluation metrics for the Decision Tree model
accuracy_dt = accuracy_score(y_test, y_pred_dt)
precision_dt = precision_score(y_test, y_pred_dt)
recall_dt = recall_score(y_test, y_pred_dt)
f1_dt = f1_score(y_test, y_pred_dt)
auc_dt = roc_auc_score(y_test, y_prob_dt)
mcc_dt = matthews_corrcoef(y_test, y_pred_dt)

print("Accuracy :", round(accuracy_dt,4))
print("AUC Score :", round(auc_dt,4))
print("Precision :", round(precision_dt,4))
print("Recall :", round(recall_dt,4))
print("F1 Score :", round(f1_dt,4))
print("MCC :", round(mcc_dt,4))

cm_dt = confusion_matrix(y_test, y_pred_dt)
#plot the the confusion matrix
disp = ConfusionMatrixDisplay(confusion_matrix=cm_dt)
disp.plot(cmap="Blues")

plt.title("Decision Tree - Confusion Matrix")
plt.show()

#Printing Classification Report
print("Classification Report")
print(classification_report(y_test, y_pred_dt))

"""# k-Nearest Neighbors"""

#k-Nearest Neighbors (kNN) Model
from sklearn.neighbors import KNeighborsClassifier

knn_model = KNeighborsClassifier(n_neighbors=5)

knn_model.fit(X_train_scaled, y_train)

print("kNN Model Trained Successfully!")

#Predictions on test data
y_pred_knn = knn_model.predict(X_test_scaled)

y_prob_knn = knn_model.predict_proba(X_test_scaled)[:,1]

# Calculate the performance evaluation metrics
accuracy_knn = accuracy_score(y_test, y_pred_knn)
precision_knn = precision_score(y_test, y_pred_knn)
recall_knn = recall_score(y_test, y_pred_knn)
f1_knn = f1_score(y_test, y_pred_knn)
auc_knn = roc_auc_score(y_test, y_prob_knn)
mcc_knn = matthews_corrcoef(y_test, y_pred_knn)

print("Accuracy :", round(accuracy_knn,4))
print("AUC Score :", round(auc_knn,4))
print("Precision :", round(precision_knn,4))
print("Recall :", round(recall_knn,4))
print("F1 Score :", round(f1_knn,4))
print("MCC :", round(mcc_knn,4))

#Confusion Matrix
cm_knn = confusion_matrix(y_test, y_pred_knn)

disp = ConfusionMatrixDisplay(confusion_matrix=cm_knn)
disp.plot(cmap="Blues")

plt.title("kNN - Confusion Matrix")
plt.show()

#Classigication report
print("Classification Report")
print(classification_report(y_test, y_pred_knn))

"""# Naive Bayes"""

#Naive Bayes MOdel
from sklearn.naive_bayes import GaussianNB

nb_model = GaussianNB()

nb_model.fit(X_train_scaled, y_train)

print("Naive Bayes Trained Successfully!")

#Prediction on test data
y_pred_nb = nb_model.predict(X_test_scaled)

y_prob_nb = nb_model.predict_proba(X_test_scaled)[:,1]

# Calculate the performance evaluation metrics
accuracy_nb = accuracy_score(y_test, y_pred_nb)
precision_nb = precision_score(y_test, y_pred_nb)
recall_nb = recall_score(y_test, y_pred_nb)
f1_nb = f1_score(y_test, y_pred_nb)
auc_nb = roc_auc_score(y_test, y_prob_nb)
mcc_nb = matthews_corrcoef(y_test, y_pred_nb)

print("Accuracy :", round(accuracy_nb,4))
print("AUC Score :", round(auc_nb,4))
print("Precision :", round(precision_nb,4))
print("Recall :", round(recall_nb,4))
print("F1 Score :", round(f1_nb,4))
print("MCC :", round(mcc_nb,4))

#Confusion Matrix
cm_nb = confusion_matrix(y_test, y_pred_nb)

disp = ConfusionMatrixDisplay(confusion_matrix=cm_nb)
disp.plot(cmap="Blues")

plt.title("Naive Bayes - Confusion Matrix")
plt.show()

#Classification report
print("Classification Report")
print(classification_report(y_test, y_pred_nb))

"""# Random Forest"""

#Random Forest Model
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

rf_model.fit(X_train_scaled, y_train)

print("Random Forest Trained Successfully!")

# Prediction on test data
y_pred_rf = rf_model.predict(X_test_scaled)

y_prob_rf = rf_model.predict_proba(X_test_scaled)[:, 1]

# Calculate the performance evaluation metrics
accuracy_rf = accuracy_score(y_test, y_pred_rf)
precision_rf = precision_score(y_test, y_pred_rf)
recall_rf = recall_score(y_test, y_pred_rf)
f1_rf = f1_score(y_test, y_pred_rf)
auc_rf = roc_auc_score(y_test, y_prob_rf)
mcc_rf = matthews_corrcoef(y_test, y_pred_rf)

print("Accuracy :", round(accuracy_rf,4))
print("AUC Score :", round(auc_rf,4))
print("Precision :", round(precision_rf,4))
print("Recall :", round(recall_rf,4))
print("F1 Score :", round(f1_rf,4))
print("MCC :", round(mcc_rf,4))

#Confusion Matrix
cm_rf = confusion_matrix(y_test, y_pred_rf)

disp = ConfusionMatrixDisplay(confusion_matrix=cm_rf)
disp.plot(cmap="Blues")

plt.title("Random Forest - Confusion Matrix")
plt.show()

#Classification Report
print("Classification Report")
print(classification_report(y_test, y_pred_rf))

"""# Model Comparison"""

#Final Comparison of all models

comparison = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Decision Tree",
        "kNN",
        "Naive Bayes",
        "Random Forest"
    ],
    "Accuracy": [
        accuracy,
        accuracy_dt,
        accuracy_knn,
        accuracy_nb,
        accuracy_rf
    ],
    "AUC": [
        auc,
        auc_dt,
        auc_knn,
        auc_nb,
        auc_rf
    ],
    "Precision": [
        precision,
        precision_dt,
        precision_knn,
        precision_nb,
        precision_rf
    ],
    "Recall": [
        recall,
        recall_dt,
        recall_knn,
        recall_nb,
        recall_rf
    ],
    "F1 Score": [
        f1,
        f1_dt,
        f1_knn,
        f1_nb,
        f1_rf
    ],
    "MCC": [
        mcc,
        mcc_dt,
        mcc_knn,
        mcc_nb,
        mcc_rf
    ]
})

comparison = comparison.round(4)
print("Model Performance Comparison")
comparison

"""# Observations

Random Forest achieved the best overall performance with the highest Accuracy (0.9205), AUC (0.9491), Precision (0.6898), F1 Score (0.6023), and MCC (0.5645). Logistic Regression achieved the highest Recall (0.8998). Therefore, Random Forest was selected as the best overall model.

| Model                        | Observation                                                                                                                                                                                                                                             |
| ---------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| **Logistic Regression**      | Achieved a strong AUC of 0.9387 and the highest recall of 0.8998. This means the model is effective at identifying customers who subscribe to a term deposit, although its precision is relatively low at 0.4347.                                       |
| **Decision Tree**            | Achieved good accuracy of 0.8956 and moderate precision, recall, and F1 score. However, its AUC of 0.7535 and MCC of 0.4929 were lower than those of the stronger models.                                                                               |
| **kNN**                      | Achieved high accuracy of 0.9053 and relatively high precision of 0.6267. However, its recall was only 0.3944, meaning that it missed a considerable number of customers who actually subscribed.                                                       |
| **Naive Bayes**              | Achieved moderate recall of 0.6175 and an AUC of 0.8606. However, its accuracy, precision, F1 score, and MCC were lower than those of the Random Forest and kNN models.                                                                                 |
| **Random Forest (Ensemble)** | Achieved the highest accuracy (0.9205), AUC (0.9491), precision (0.6898), F1 score (0.6023), and MCC (0.5645). It provided the strongest overall performance across the evaluation metrics and was selected as the best overall model for this dataset. |

# Streamlit Application Development
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile model.py
# 
# # ============================================================
# # BANK MARKETING - MODEL DEVELOPMENT
# # ============================================================
# 
# 
# 
# # ============================================================
# #  IMPORT LIBRARIES
# # ============================================================
# 
# import os
# import joblib
# import numpy as np
# import pandas as pd
# 
# from sklearn.model_selection import train_test_split
# from sklearn.preprocessing import LabelEncoder, StandardScaler
# 
# from sklearn.linear_model import LogisticRegression
# from sklearn.tree import DecisionTreeClassifier
# from sklearn.neighbors import KNeighborsClassifier
# from sklearn.naive_bayes import GaussianNB
# from sklearn.ensemble import RandomForestClassifier
# 
# from sklearn.metrics import (
#     accuracy_score,
#     roc_auc_score,
#     precision_score,
#     recall_score,
#     f1_score,
#     matthews_corrcoef,
#     confusion_matrix,
#     classification_report
# )
# 
# 
# # ============================================================
# #  CREATE MODEL DIRECTORY
# # ============================================================
# 
# os.makedirs("model", exist_ok=True)
# 
# print("Model directory ready.")
# 
# 
# # ============================================================
# # LOAD DATASET
# # ============================================================
# 
# data = pd.read_csv(
#     "bank-additional-full.csv",
#     sep=";"
# )
# 
# print("\nDataset loaded successfully.")
# print("Dataset shape:", data.shape)
# 
# 
# # ============================================================
# # SEPARATE FEATURES AND TARGET
# # ============================================================
# 
# X = data.drop(columns=["y"]).copy()
# y = data["y"].copy()
# 
# 
# # ============================================================
# # ENCODE TARGET VARIABLE
# # ============================================================
# 
# target_encoder = LabelEncoder()
# 
# y = target_encoder.fit_transform(y)
# 
# print("\nTarget classes:")
# print(target_encoder.classes_)
# 
# # no  -> 0
# # yes -> 1
# 
# 
# # ============================================================
# # ENCODE CATEGORICAL FEATURES
# # ============================================================
# 
# label_encoders = {}
# 
# for column in X.columns:
# 
#     if X[column].dtype == "object":
# 
#         encoder = LabelEncoder()
# 
#         X[column] = encoder.fit_transform(
#             X[column].astype(str)
#         )
# 
#         label_encoders[column] = encoder
# 
# 
# print("\nCategorical features encoded:")
# print(list(label_encoders.keys()))
# 
# 
# # ============================================================
# #  TRAIN-TEST SPLIT
# # ============================================================
# 
# X_train, X_test, y_train, y_test = train_test_split(
#     X,
#     y,
#     test_size=0.20,
#     random_state=42,
#     stratify=y
# )
# 
# print("\nTrain/Test split completed.")
# print("Training data:", X_train.shape)
# print("Testing data :", X_test.shape)
# 
# 
# # ============================================================
# # FEATURE SCALING
# # ============================================================
# 
# scaler = StandardScaler()
# 
# X_train_scaled = scaler.fit_transform(X_train)
# X_test_scaled = scaler.transform(X_test)
# 
# print("\nFeature scaling completed.")
# 
# 
# # ============================================================
# # DEFINE MODELS
# # ============================================================
# 
# model = {
# 
#     # --------------------------------------------------------
#     # Logistic Regression
#     # --------------------------------------------------------
#     "Logistic Regression":
#         LogisticRegression(
#             random_state=42,
#             max_iter=1000,
#             class_weight="balanced"
#         ),
# 
#     # --------------------------------------------------------
#     # Decision Tree
#     # --------------------------------------------------------
#     "Decision Tree":
#         DecisionTreeClassifier(
#             random_state=42
#         ),
# 
#     # --------------------------------------------------------
#     # k-Nearest Neighbors
#     # --------------------------------------------------------
#     "K-Nearest Neighbors":
#         KNeighborsClassifier(),
# 
#     # --------------------------------------------------------
#     # Naive Bayes
#     # --------------------------------------------------------
#     "Naive Bayes":
#         GaussianNB(),
# 
#     # --------------------------------------------------------
#     # Random Forest
#     # --------------------------------------------------------
#     "Random Forest":
#         RandomForestClassifier(
#             n_estimators=100,
#             random_state=42,
#             n_jobs=-1
#         )
# }
# 
# 
# # ============================================================
# #  TRAIN AND EVALUATE MODELS
# # ============================================================
# 
# results = []
# 
# trained_model = {}
# 
# print("\n" + "=" * 70)
# print("MODEL TRAINING AND EVALUATION")
# print("=" * 70)
# 
# 
# for name, model in model.items():
# 
#     print("\nTraining:", name)
# 
#     # Train model
#     model.fit(
#         X_train_scaled,
#         y_train
#     )
# 
#     # Store trained model
#     trained_model[name] = model
# 
#     # Generate predictions
#     y_pred = model.predict(
#         X_test_scaled
#     )
# 
#     # Generate probability/decision scores for AUC
#     if hasattr(model, "predict_proba"):
# 
#         y_prob = model.predict_proba(
#             X_test_scaled
#         )[:, 1]
# 
#     else:
# 
#         y_prob = model.decision_function(
#             X_test_scaled
#         )
# 
#     # --------------------------------------------------------
#     # Evaluation metrics
#     # --------------------------------------------------------
# 
#     accuracy = accuracy_score(
#         y_test,
#         y_pred
#     )
# 
#     auc = roc_auc_score(
#         y_test,
#         y_prob
#     )
# 
#     precision = precision_score(
#         y_test,
#         y_pred,
#         zero_division=0
#     )
# 
#     recall = recall_score(
#         y_test,
#         y_pred,
#         zero_division=0
#     )
# 
#     f1 = f1_score(
#         y_test,
#         y_pred,
#         zero_division=0
#     )
# 
#     mcc = matthews_corrcoef(
#         y_test,
#         y_pred
#     )
# 
#     # --------------------------------------------------------
#     # Store results
#     # --------------------------------------------------------
# 
#     results.append({
#         "Model": name,
#         "Accuracy": accuracy,
#         "AUC": auc,
#         "Precision": precision,
#         "Recall": recall,
#         "F1 Score": f1,
#         "MCC": mcc
#     })
# 
#     # --------------------------------------------------------
#     # Display results
#     # --------------------------------------------------------
# 
#     print("\n", name)
#     print("-" * 50)
# 
#     print("Accuracy :", round(accuracy, 4))
#     print("AUC      :", round(auc, 4))
#     print("Precision:", round(precision, 4))
#     print("Recall   :", round(recall, 4))
#     print("F1 Score :", round(f1, 4))
#     print("MCC      :", round(mcc, 4))
# 
# 
# # ============================================================
# #  MODEL COMPARISON
# # ============================================================
# 
# comparison = pd.DataFrame(
#     results
# )
# 
# comparison = comparison.round(4)
# 
# print("\n")
# print("=" * 70)
# print("MODEL PERFORMANCE COMPARISON")
# print("=" * 70)
# 
# print(
#     comparison.to_string(
#         index=False
#     )
# )
# 
# 
# # ============================================================
# # CONFUSION MATRIX AND CLASSIFICATION REPORT
# # ============================================================
# 
# print("\n")
# print("=" * 70)
# print("CONFUSION MATRICES AND CLASSIFICATION REPORTS")
# print("=" * 70)
# 
# 
# for name, model in trained_model.items():
# 
#     y_pred = model.predict(
#         X_test_scaled
#     )
# 
#     print("\n")
#     print("=" * 70)
#     print(name)
#     print("=" * 70)
# 
#     # Confusion Matrix
#     cm = confusion_matrix(
#         y_test,
#         y_pred
#     )
# 
#     print("\nConfusion Matrix:")
#     print(cm)
# 
#     # Classification Report
#     print("\nClassification Report:")
# 
#     print(
#         classification_report(
#             y_test,
#             y_pred,
#             target_names=target_encoder.classes_,
#             zero_division=0
#         )
#     )
# 
# 
# # ============================================================
# # IDENTIFY BEST MODEL
# # ============================================================
# 
# best_model_name = comparison.loc[
#     comparison["Accuracy"].idxmax(),
#     "Model"
# ]
# 
# print("\n")
# print("=" * 70)
# print("BEST MODEL")
# print("=" * 70)
# 
# print(
#     "Best model based on Accuracy:",
#     best_model_name
# )
# 
# 
# # ============================================================
# # SAVE TRAINED MODELS
# # ============================================================
# 
# joblib.dump(
#     trained_model["Logistic Regression"],
#     "model/logistic_regression.pkl"
# )
# 
# joblib.dump(
#     trained_model["Decision Tree"],
#     "model/decision_tree.pkl"
# )
# 
# joblib.dump(
#     trained_model["K-Nearest Neighbors"],
#     "model/knn.pkl"
# )
# 
# joblib.dump(
#     trained_model["Naive Bayes"],
#     "model/naive_bayes.pkl"
# )
# 
# joblib.dump(
#     trained_model["Random Forest"],
#     "model/random_forest.pkl"
# )
# 
# print("\nAll ML models saved successfully.")
# 
# 
# # ============================================================
# # SAVE SCALER
# # ============================================================
# 
# joblib.dump(
#     scaler,
#     "model/scaler.pkl"
# )
# 
# print("Scaler saved successfully.")
# 
# 
# # ============================================================
# #  SAVE FEATURE LABEL ENCODERS
# # ============================================================
# 
# joblib.dump(
#     label_encoders,
#     "model/label_encoders.pkl"
# )
# 
# print("Feature label encoders saved successfully.")
# 
# 
# # ============================================================
# #  SAVE TARGET ENCODER
# # ============================================================
# 
# joblib.dump(
#     target_encoder,
#     "model/target_encoder.pkl"
# )
# 
# print("Target encoder saved successfully.")
# 
# 
# # ============================================================
# # SAVE MODEL COMPARISON
# # ============================================================
# 
# comparison.to_csv(
#     "model_comparison.csv",
#     index=False
# )
# 
# print("Model comparison table saved successfully.")
# 
# 
# # ============================================================
# # SAVE ORIGINAL TEST DATA
# # ============================================================
# 
# # X_test contains encoded/scaled data.
# # We use the original dataset index to retrieve the
# # original human-readable test rows.
# 
# test_data_original = data.loc[
#     X_test.index
# ].copy()
# 
# test_data_original.to_csv(
#     "test_data.csv",
#     index=False
# )
# 
# print("Original test data saved successfully.")
# 
# 
# # ============================================================
# # FINAL SUMMARY
# # ============================================================
# 
# print("\n")
# print("=" * 70)
# print("MODEL DEVELOPMENT COMPLETED SUCCESSFULLY")
# print("=" * 70)
# 
# print("\nGenerated model files:")
# 
# print("  - logistic_regression.pkl")
# print("  - decision_tree.pkl")
# print("  - knn.pkl")
# print("  - naive_bayes.pkl")
# print("  - random_forest.pkl")
# print("  - scaler.pkl")
# print("  - label_encoders.pkl")
# print("  - target_encoder.pkl")
# 
# print("\nGenerated project files:")
# 
# print("  - model_comparison.csv")
# print("  - test_data.csv")
# 
# print("\nModel development pipeline completed.")

#Running Model development Pipline

!python model.py

# Check the final model comparison table

import pandas as pd

comparison = pd.read_csv("model_comparison.csv")

print("FINAL MODEL COMPARISON")
print("=" * 60)

display(comparison.round(4))

"""# Creating App.py"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# # ============================================================
# # BANK MARKETING PREDICTION - STREAMLIT APPLICATION
# # ============================================================
# 
# 
# # ============================================================
# # IMPORT LIBRARIES
# # ============================================================
# 
# import streamlit as st
# import pandas as pd
# import numpy as np
# import joblib
# 
# from sklearn.metrics import (
#     accuracy_score,
#     roc_auc_score,
#     precision_score,
#     recall_score,
#     f1_score,
#     matthews_corrcoef,
#     confusion_matrix,
#     classification_report
# )
# 
# 
# # ============================================================
# # PAGE CONFIGURATION
# # ============================================================
# 
# st.set_page_config(
#     page_title="Bank Marketing Prediction",
#     page_icon="🏦",
#     layout="wide"
# )
# 
# 
# # ============================================================
# # APPLICATION TITLE
# # ============================================================
# 
# st.title("🏦 Bank Marketing Prediction System")
# 
# st.markdown(
#     """
#     This application predicts whether a bank customer will
#     subscribe to a **Bank Term Deposit** using Machine Learning.
# 
#     Upload a test CSV file, select a model, and generate
#     predictions along with evaluation metrics.
#     """
# )
# 
# st.divider()
# 
# 
# # ============================================================
# #  LOAD TRAINED MODELS AND PREPROCESSING OBJECTS
# # ============================================================
# 
# log_model = joblib.load(
#     "model/logistic_regression.pkl"
# )
# 
# dt_model = joblib.load(
#     "model/decision_tree.pkl"
# )
# 
# knn_model = joblib.load(
#     "model/knn.pkl"
# )
# 
# nb_model = joblib.load(
#     "model/naive_bayes.pkl"
# )
# 
# rf_model = joblib.load(
#     "model/random_forest.pkl"
# )
# 
# scaler = joblib.load(
#     "model/scaler.pkl"
# )
# 
# label_encoders = joblib.load(
#     "model/label_encoders.pkl"
# )
# 
# 
# # ============================================================
# # EXPECTED INPUT FEATURES
# # ============================================================
# 
# expected_columns = [
#     "age",
#     "job",
#     "marital",
#     "education",
#     "default",
#     "housing",
#     "loan",
#     "contact",
#     "month",
#     "day_of_week",
#     "duration",
#     "campaign",
#     "pdays",
#     "previous",
#     "poutcome",
#     "emp.var.rate",
#     "cons.price.idx",
#     "cons.conf.idx",
#     "euribor3m",
#     "nr.employed"
# ]
# 
# 
# # ============================================================
# #  MODEL SELECTION
# # ============================================================
# 
# st.sidebar.title("Model Selection")
# 
# selected_model = st.sidebar.selectbox(
#     "Choose Machine Learning Model",
#     [
#         "Logistic Regression",
#         "Decision Tree",
#         "k-Nearest Neighbors",
#         "Naive Bayes",
#         "Random Forest"
#     ]
# )
# 
# st.sidebar.success(
#     f"Selected Model : {selected_model}"
# )
# 
# st.sidebar.markdown("---")
# 
# 
# # ============================================================
# # FILE UPLOAD
# # ============================================================
# 
# uploaded_file = st.sidebar.file_uploader(
#     "Upload Test CSV File",
#     type=["csv"]
# )
# 
# 
# # ============================================================
# # PROCESS UPLOADED FILE
# # ============================================================
# 
# if uploaded_file is not None:
# 
#     try:
# 
#         # ----------------------------------------------------
#         # READ THE UPLOADED CSV
#         # ----------------------------------------------------
# 
#         data = pd.read_csv(
#             uploaded_file,
#             sep=None,
#             engine="python"
#         )
# 
# 
#         # ----------------------------------------------------
#         # KEEP ORIGINAL DATA UNCHANGED
#         # ----------------------------------------------------
# 
#         original_data = data.copy()
# 
# 
#         # ----------------------------------------------------
#         # DISPLAY ORIGINAL DATA
#         # ----------------------------------------------------
# 
#         st.subheader("Uploaded Dataset")
# 
#         st.info(
#             "The table below shows the original uploaded data. "
#             "Categorical values are kept in their original form."
#         )
# 
#         st.dataframe(
#             original_data.head(10),
#             use_container_width=True
#         )
# 
# 
#         # ----------------------------------------------------
#         # SHOW DATASET INFORMATION
#         # ----------------------------------------------------
# 
#         st.write(
#             f"Dataset shape: **{original_data.shape[0]} rows × "
#             f"{original_data.shape[1]} columns**"
#         )
# 
# 
#         # ====================================================
#         #  KEEP TARGET FOR EVALUATION IF AVAILABLE
#         # ====================================================
# 
#         if "y" in original_data.columns:
# 
#             y_original = original_data["y"].copy()
# 
#         else:
# 
#             y_original = None
# 
# 
#         # ====================================================
#         #  CREATE SEPARATE DATA FOR ML PROCESSING
#         # ====================================================
# 
#         prediction_data = original_data.copy()
# 
# 
#         # ----------------------------------------------------
#         # REMOVE TARGET COLUMN
#         # ----------------------------------------------------
# 
#         if "y" in prediction_data.columns:
# 
#             prediction_data = prediction_data.drop(
#                 columns=["y"]
#             )
# 
# 
#         # ====================================================
#         #  CHECK REQUIRED FEATURES
#         # ====================================================
# 
#         missing_columns = [
#             column
#             for column in expected_columns
#             if column not in prediction_data.columns
#         ]
# 
#         if len(missing_columns) > 0:
# 
#             st.error(
#                 "The uploaded CSV is missing the following "
#                 "required columns:"
#             )
# 
#             st.write(missing_columns)
# 
#             st.info(
#                 "Please upload a Bank Marketing test CSV "
#                 "containing the 20 input features."
#             )
# 
#             st.stop()
# 
# 
# 
# 
#         extra_columns = [
#             column
#             for column in prediction_data.columns
#             if column not in expected_columns
#         ]
# 
#         if len(extra_columns) > 0:
# 
#             st.warning(
#                 "Extra columns were detected. "
#                 "They will not be used for prediction:"
#             )
# 
#             st.write(extra_columns)
# 
# 
#         # ====================================================
#         # SELECT FEATURES IN TRAINING ORDER
#         # ====================================================
# 
#         prediction_data = prediction_data[
#             expected_columns
#         ].copy()
# 
# 
#         # ====================================================
#         # APPLY THE SAME LABEL ENCODING USED DURING TRAINING
#         # ====================================================
# 
# 
#         for column, encoder in label_encoders.items():
# 
#             if column not in prediction_data.columns:
#                 continue
# 
# 
#             # Convert values to strings because the encoders
#             # were trained on string categorical values.
# 
#             column_values = (
#                 prediction_data[column]
#                 .astype(str)
#                 .str.strip()
#             )
# 
# 
#             # Classes learned during training
# 
#             known_classes = set(
#                 encoder.classes_
#             )
# 
# 
#             # Find categories not seen during training
# 
#             unknown_values = sorted(
#                 set(column_values) - known_classes
#             )
# 
# 
#             if len(unknown_values) > 0:
# 
#                 st.warning(
#                     f"Unknown value(s) found in '{column}': "
#                     f"{unknown_values[:5]}. "
#                     "These values will be replaced by the "
#                     "first known training category."
#                 )
# 
#                 replacement_value = (
#                     encoder.classes_[0]
#                 )
# 
#                 column_values = column_values.apply(
#                     lambda value:
#                     value
#                     if value in known_classes
#                     else replacement_value
#                 )
# 
# 
#             # Apply the SAME encoder used during training
# 
#             prediction_data[column] = (
#                 encoder.transform(
#                     column_values
#                 )
#             )
# 
# 
#         # ====================================================
#         # CONVERT NUMERIC FEATURES TO NUMERIC TYPE
#         # ====================================================
# 
#         for column in expected_columns:
# 
#             if column not in label_encoders:
# 
#                 prediction_data[column] = pd.to_numeric(
#                     prediction_data[column],
#                     errors="coerce"
#                 )
# 
# 
#         # ====================================================
#         # HANDLE MISSING / INVALID VALUES
#         # ====================================================
# 
#         if prediction_data.isnull().sum().sum() > 0:
# 
#             st.warning(
#                 "Missing or invalid numeric values were detected. "
#                 "They will be replaced with 0 for prediction."
#             )
# 
#             prediction_data = prediction_data.fillna(0)
# 
# 
#         # ====================================================
#         # SCALE USING THE SAVED TRAINING SCALER
#         # ====================================================
# 
#         prediction_data_scaled = scaler.transform(
#             prediction_data
#         )
# 
# 
#         # ====================================================
#         #  SELECT TRAINED MODEL
#         # ====================================================
# 
#         if selected_model == "Logistic Regression":
# 
#             model = log_model
# 
#         elif selected_model == "Decision Tree":
# 
#             model = dt_model
# 
#         elif selected_model == "k-Nearest Neighbors":
# 
#             model = knn_model
# 
#         elif selected_model == "Naive Bayes":
# 
#             model = nb_model
# 
#         else:
# 
#             model = rf_model
# 
# 
#         # ====================================================
#         # PREDICTION BUTTON
#         # ====================================================
# 
#         if st.button(
#             "Predict",
#             type="primary"
#         ):
# 
#             # ------------------------------------------------
#             # Generate predictions
#             # ------------------------------------------------
# 
#             # Models trained with scaled features
#             if selected_model in [
#                 "Logistic Regression",
#                 "k-Nearest Neighbors",
#                 "Naive Bayes"
#             ]:
#                 model_input = prediction_data_scaled
# 
#             # Models trained with unscaled encoded features
#             else:
#                 model_input = prediction_data_scaled
# 
#             predictions = model.predict(model_input)
# 
#             # ------------------------------------------------
#             # Convert predictions to Yes / No
#             # ------------------------------------------------
# 
#             prediction_labels = np.where(
#                 predictions == 1,
#                 "Yes",
#                 "No"
#             )
# 
# 
#             # =================================================
#             #  CREATE RESULT USING ORIGINAL DATA
#             # =================================================
# 
#             result = original_data.copy()
# 
#             result["Prediction"] = (
#                 prediction_labels
#             )
# 
# 
#             # =================================================
#             #  DISPLAY PREDICTION RESULTS
#             # =================================================
# 
#             st.subheader(
#                 "Prediction Results"
#             )
# 
#             st.dataframe(
#                 result,
#                 use_container_width=True
#             )
# 
# 
#             # =================================================
#             #  PREDICTION SUMMARY
#             # =================================================
# 
#             yes_count = np.sum(
#                 prediction_labels == "Yes"
#             )
# 
#             no_count = np.sum(
#                 prediction_labels == "No"
#             )
# 
# 
#             col1, col2 = st.columns(2)
# 
# 
#             with col1:
# 
#                 st.metric(
#                     "Predicted Yes",
#                     int(yes_count)
#                 )
# 
# 
#             with col2:
# 
#                 st.metric(
#                     "Predicted No",
#                     int(no_count)
#                 )
# 
# 
#             # =================================================
#             # EVALUATION
#             # =================================================
# 
#             if y_original is not None:
# 
#                 # ------------------------------------------------
#                 # Convert actual target to 0 / 1
#                 # ------------------------------------------------
# 
#                 y_text = (
#                     y_original
#                     .astype(str)
#                     .str.strip()
#                     .str.lower()
#                 )
# 
# 
#                 y_true = y_text.map({
#                     "no": 0,
#                     "yes": 1
#                 })
# 
# 
#                 # ------------------------------------------------
#                 # Handle numeric 0/1 target if supplied
#                 # ------------------------------------------------
# 
#                 if y_true.isnull().any():
# 
#                     y_true = pd.to_numeric(
#                         y_original,
#                         errors="coerce"
#                     )
# 
# 
#                 if y_true.isnull().any():
# 
#                     st.error(
#                         "The target column 'y' contains values "
#                         "that could not be interpreted as No/Yes "
#                         "or 0/1."
#                     )
# 
#                     st.stop()
# 
# 
#                 y_true = y_true.astype(int).values
# 
# 
#                 # =================================================
#                 # CALCULATE METRICS
#                 # =================================================
# 
#                 accuracy = accuracy_score(
#                     y_true,
#                     predictions
#                 )
# 
#                 precision = precision_score(
#                     y_true,
#                     predictions,
#                     zero_division=0
#                 )
# 
#                 recall = recall_score(
#                     y_true,
#                     predictions,
#                     zero_division=0
#                 )
# 
#                 f1 = f1_score(
#                     y_true,
#                     predictions,
#                     zero_division=0
#                 )
# 
#                 mcc = matthews_corrcoef(
#                     y_true,
#                     predictions
#                 )
# 
# 
#                 # ------------------------------------------------
#                 # AUC
#                 # ------------------------------------------------
# 
#                 try:
# 
#                     if hasattr(
#                         model,
#                         "predict_proba"
#                     ):
# 
#                         probabilities = (
#                             model
#                             .predict_proba(
#                                 model_input
#                             )[:, 1]
#                         )
# 
#                     else:
# 
#                         probabilities = (
#                             model
#                             .decision_function(
#                                 model_input
#                             )
#                         )
# 
# 
#                     auc = roc_auc_score(
#                         y_true,
#                         probabilities
#                     )
# 
#                 except Exception:
# 
#                     auc = np.nan
# 
# 
#                 # =================================================
#                 #DISPLAY METRICS
#                 # =================================================
# 
#                 st.subheader(
#                     "Model Evaluation Metrics"
#                 )
# 
# 
#                 col1, col2, col3 = st.columns(3)
# 
# 
#                 with col1:
# 
#                     st.metric(
#                         "Accuracy",
#                         f"{accuracy:.4f}"
#                     )
# 
# 
#                 with col2:
# 
#                     if np.isnan(auc):
# 
#                         st.metric(
#                             "AUC",
#                             "N/A"
#                         )
# 
#                     else:
# 
#                         st.metric(
#                             "AUC",
#                             f"{auc:.4f}"
#                         )
# 
# 
#                 with col3:
# 
#                     st.metric(
#                         "Precision",
#                         f"{precision:.4f}"
#                     )
# 
# 
#                 col4, col5, col6 = st.columns(3)
# 
# 
#                 with col4:
# 
#                     st.metric(
#                         "Recall",
#                         f"{recall:.4f}"
#                     )
# 
# 
#                 with col5:
# 
#                     st.metric(
#                         "F1 Score",
#                         f"{f1:.4f}"
#                     )
# 
# 
#                 with col6:
# 
#                     st.metric(
#                         "MCC",
#                         f"{mcc:.4f}"
#                     )
# 
# 
#                 # =================================================
#                 #  CONFUSION MATRIX
#                 # =================================================
# 
#                 st.subheader(
#                     "Confusion Matrix"
#                 )
# 
# 
#                 cm = confusion_matrix(
#                     y_true,
#                     predictions
#                 )
# 
# 
#                 cm_df = pd.DataFrame(
#                     cm,
#                     index=[
#                         "Actual No",
#                         "Actual Yes"
#                     ],
#                     columns=[
#                         "Predicted No",
#                         "Predicted Yes"
#                     ]
#                 )
# 
# 
#                 st.dataframe(
#                     cm_df,
#                     use_container_width=True
#                 )
# 
# 
#                 # =================================================
#                 # CLASSIFICATION REPORT
#                 # =================================================
# 
#                 st.subheader(
#                     "Classification Report"
#                 )
# 
# 
#                 report = classification_report(
#                     y_true,
#                     predictions,
#                     target_names=[
#                         "No",
#                         "Yes"
#                     ],
#                     output_dict=True,
#                     zero_division=0
#                 )
# 
# 
#                 report_df = (
#                     pd.DataFrame(report)
#                     .transpose()
#                     .round(4)
#                 )
# 
# 
#                 st.dataframe(
#                     report_df,
#                     use_container_width=True
#                 )
# 
# 
#             else:
# 
#                 st.info(
#                     "The uploaded file does not contain a 'y' "
#                     "column. Predictions are available, but "
#                     "evaluation metrics cannot be calculated."
#                 )
# 
# 
#             # =================================================
#             #  DOWNLOAD ORIGINAL DATA + PREDICTION
#             # =================================================
# 
#             csv = result.to_csv(
#                 index=False,
#                 sep=";"
#             ).encode("utf-8")
# 
# 
#             st.download_button(
#                 label="Download Predictions",
#                 data=csv,
#                 file_name="bank_marketing_predictions.csv",
#                 mime="text/csv"
#             )
# 
# 
#             # =================================================
#             #  SUCCESS MESSAGE
#             # =================================================
# 
#             st.success(
#                 f"Prediction completed successfully using "
#                 f"{selected_model}!"
#             )
# 
# 
#     except Exception as e:
# 
#         st.error(
#             "An error occurred while processing the uploaded file."
#         )
# 
#         st.exception(e)

!pip install -q streamlit

!pkill -f streamlit || true

!nohup streamlit run app.py \
    --server.address 0.0.0.0 \
    --server.port 8501 \
    --server.enableCORS false \
    --server.enableXsrfProtection false \
    --browser.gatherUsageStats false \
    > /content/streamlit.log 2>&1 &

!cat /content/streamlit.log

from google.colab import output
output.serve_kernel_port_as_iframe(8501)

"""# Creating requirement.txt file"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# 
# # Used to create and run the Streamlit
# # machine learning prediction application.
# streamlit==1.61.1
# 
# # Used for loading, cleaning, manipulating,and displaying the Bank Marketing dataset.
# pandas==2.2.2
# 
# # Used for numerical calculations and arrays.
# numpy==2.0.2
# 
# 
# # Used to build, train, evaluate, and use the Machine Learning classification models:
# # Logistic Regression
# # Decision Tree
# # k-Nearest Neighbors
# # Naive Bayes
# # Random Forest
# scikit-learn==1.6.1
# 
# 
# # Used to save and load trained ML models,
# # scaler, and label encoders as .pkl files.
# joblib==1.5.3
# 
# # Used for creating plots and visualizations
# # during model development and analysis.
# matplotlib==3.10.0
# 
# # Used for statistical data visualization
# # during exploratory data analysis.
# seaborn==0.13.2

# Commented out IPython magic to ensure Python compatibility.
# %%writefile README.md
# 
# # Bank Marketing Subscription Prediction
# 
# ## Problem Statement
# 
# The objective of this project is to develop a Machine Learning classification system
# to predict whether a bank customer will subscribe to a term deposit.
# 
# The project uses the Bank Marketing dataset from the UCI Machine Learning Repository
# and compares five different Machine Learning classification algorithms.
# 
# The target variable is:
# 
# - `y = yes` → Customer subscribes to a term deposit
# - `y = no` → Customer does not subscribe to a term deposit
# 
# The trained Machine Learning models are integrated into a Streamlit web application.
# The application allows a user to upload a CSV file, select a Machine Learning model,
# and obtain predictions for the customers in the uploaded dataset.
# 
# ---
# 
# ## Dataset Description
# 
# The project uses the **Bank Marketing dataset** obtained from the
# **UCI Machine Learning Repository**.
# 
# The dataset contains information related to customer demographics, previous
# marketing campaigns, contact information and economic indicators.
# 
# The dataset contains **20 input features** and one target variable.
# 
# ### Input Features
# 
# The main input features include:
# 
# - age
# - job
# - marital
# - education
# - default
# - housing
# - loan
# - contact
# - month
# - day_of_week
# - duration
# - campaign
# - pdays
# - previous
# - poutcome
# - emp.var.rate
# - cons.price.idx
# - cons.conf.idx
# - euribor3m
# - nr.employed
# 
# ### Target Variable
# 
# The target variable is:
# 
# - `yes` – customer subscribed to a term deposit
# - `no` – customer did not subscribe to a term deposit
# 
# The complete dataset used during model development is:
# 
# - `bank-additional-full.csv` – contains 41,188 examples and 20 input features.
# 
# The data was preprocessed before training the Machine Learning models.
# Categorical variables were label encoded and numerical features were scaled
# where required.
# 
# ---
# 
# ## GitHub Repository
# 
# The complete project is maintained in the following GitHub repository:
# 
# **GitHub Repository:**
# 
# https://github.com/2025ad05008/Bank-Marketing
# 
# The repository contains the Machine Learning notebook, trained models,
# preprocessing files, Streamlit application, requirements file,
# test data and project documentation.
# 
# ---
# 
# ## Machine Learning Models Used
# 
# Five Machine Learning classification models were developed and evaluated:
# 
# 1. Logistic Regression
# 2. Decision Tree
# 3. k-Nearest Neighbors (kNN)
# 4. Naive Bayes
# 5. Random Forest (Ensemble)
# 
# The trained models and preprocessing objects are saved using Joblib and are
# used by the Streamlit application for prediction.
# 
# ---
# 
# ## Data Preprocessing
# 
# The following preprocessing steps were performed before model training:
# 
# 1. The dataset was separated into input features and the target variable.
# 2. Categorical features were converted into numerical values using
#    `LabelEncoder`.
# 3. The target variable was encoded into numerical form for model training.
# 4. The dataset was divided into training and testing sets using an 80:20 split.
# 5. Stratified splitting was used to preserve the class distribution.
# 6. `StandardScaler` was used to scale the features required by models such as
#    Logistic Regression, kNN and Naive Bayes.
# 7. The same saved encoders and scaler are used during prediction in the
#    Streamlit application.
# 
# The training-test split produced:
# 
# - Training samples: **32,950**
# - Testing samples: **8,238**
# - Input features: **20**
# 
# ---
# 
# ## Model Evaluation
# 
# The models were evaluated using the following performance metrics:
# 
# - Accuracy
# - AUC
# - Precision
# - Recall
# - F1 Score
# - Matthews Correlation Coefficient (MCC)
# 
# ### Model Comparison
# 
# | ML Model                 | Accuracy |    AUC | Precision | Recall | F1 Score |    MCC |
# | ------------------------ | -------: | -----: | --------: | -----: | -------: | -----: |
# | Logistic Regression      |   0.8569 | 0.9387 |    0.4347 | 0.8998 |   0.5862 | 0.5617 |
# | Decision Tree            |   0.8956 | 0.7535 |    0.5343 | 0.5700 |   0.5516 | 0.4929 |
# | kNN                      |   0.9053 | 0.8617 |    0.6267 | 0.3944 |   0.4841 | 0.4491 |
# | Naive Bayes              |   0.8536 | 0.8606 |    0.4024 | 0.6175 |   0.4872 | 0.4189 |
# | Random Forest (Ensemble) |   0.9205 | 0.9491 |    0.6898 | 0.5345 |   0.6023 | 0.5645 |
# 
# ---
# 
# ## Observations on Model Performance
# 
# ### Logistic Regression
# 
# Logistic Regression achieved an accuracy of **0.8569** and an AUC of
# **0.9387**.
# 
# It achieved the **highest recall of 0.8998** among all five models, meaning
# that it was highly effective at identifying customers who actually subscribed
# to the term deposit.
# 
# However, its precision was relatively low at **0.4347**, indicating that a
# considerable number of positive predictions were false positives.
# 
# Overall, Logistic Regression performed particularly well when recall was
# considered important.
# 
# ### Decision Tree
# 
# The Decision Tree achieved an accuracy of **0.8956**.
# 
# Its AUC was **0.7535**, which was the lowest AUC among the five models.
# 
# Precision and recall were relatively balanced at **0.5343** and **0.5700**,
# respectively. The model achieved reasonable accuracy but did not perform as
# well as the other models in terms of AUC and MCC.
# 
# ### k-Nearest Neighbors (kNN)
# 
# kNN achieved an accuracy of **0.9053** and the **highest precision of 0.6267**
# among the models.
# 
# However, its recall was relatively low at **0.3944**. This indicates that
# although its positive predictions were comparatively precise, it failed to
# identify a significant number of customers who actually subscribed.
# 
# Its F1 score and MCC were also lower than those of Logistic Regression and
# Random Forest.
# 
# ### Naive Bayes
# 
# Naive Bayes achieved an accuracy of **0.8536** and an AUC of **0.8606**.
# 
# Its recall was **0.6175**, which was higher than Decision Tree and kNN, while
# its precision was relatively low at **0.4024**.
# 
# Its F1 score of **0.4872** and MCC of **0.4189** were lower than those of the
# stronger-performing models.
# 
# ### Random Forest (Ensemble)
# 
# Random Forest achieved the **highest accuracy of 0.9205** and the
# **highest AUC of 0.9491** among all five models.
# 
# It also achieved the:
# 
# - Highest precision: **0.6898**
# - Highest F1 Score: **0.6023**
# - Highest MCC: **0.5645**
# 
# Although its recall of **0.5345** was lower than Logistic Regression and
# Naive Bayes, Random Forest provided the strongest overall balance across
# the major evaluation metrics.
# 
# Therefore, **Random Forest was selected as the best-performing model for
# this dataset**.
# 
# ---
# 
# ## Overall Winner
# 
# ### Random Forest (Ensemble)
# 
# Random Forest is selected as the overall best model because it provides the
# best overall combination of:
# 
# - Accuracy: **0.9205**
# - AUC: **0.9491**
# - Precision: **0.6898**
# - F1 Score: **0.6023**
# - MCC: **0.5645**
# 
# Although Logistic Regression achieved a higher recall (**0.8998**) than
# Random Forest (**0.5345**), Random Forest performed better on the majority
# of the evaluation metrics and therefore was selected as the overall winner.
# 
# ---
# 
# ## Streamlit Web Application
# 
# The trained Machine Learning models are integrated into a Streamlit web
# application.
# 
# The application provides the following functionality:
# 
# 1. Select a Machine Learning model.
# 2. Upload a CSV test dataset.
# 3. Display the uploaded customer data.
# 4. Automatically preprocess categorical and numerical features.
# 5. Apply the same preprocessing objects used during model training.
# 6. Generate predictions using the selected Machine Learning model.
# 7. Display predictions as **Yes** or **No**.
# 8. Display evaluation metrics when the uploaded dataset contains the target
#    variable.
# 9. Display a confusion matrix.
# 10. Display a classification report.
# 11. Download the prediction results as a CSV file.
# 
# The application keeps the original uploaded dataset unchanged for display and
# uses a separate processed copy internally for Machine Learning prediction.
# 
# ---
# 
# ## Model Files
# 
# The trained Machine Learning models and preprocessing objects are saved using
# Joblib.
# 
# The following model files are generated:
# 
# - `logistic_regression.pkl`
# - `decision_tree.pkl`
# - `knn.pkl`
# - `naive_bayes.pkl`
# - `random_forest.pkl`
# 
# The preprocessing files are:
# 
# - `scaler.pkl`
# - `label_encoders.pkl`
# - `target_encoder.pkl`
# 
# These saved files allow the Streamlit application to load the trained models
# and apply the same preprocessing used during model development.
# 
# ---
# 
# ## Project Structure
# 
# The main project structure is:
# 
# ```text
# Bank-Marketing/
# │
# ├── app.py
# ├── model.py
# ├── README.md
# ├── requirements.txt
# ├── test_data.csv
# ├── model_comparison.csv
# ├── 2025ad05008.py
# │
# └── model/
#     ├── logistic_regression.pkl
#     ├── decision_tree.pkl
#     ├── knn.pkl
#     ├── naive_bayes.pkl
#     ├── random_forest.pkl
#     ├── scaler.pkl
#     ├── label_encoders.pkl
#     └── target_encoder.pkl